config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # 日記カレンダー機能
  resources :diaries, only: %i[index new create show] do
    get 'completion', on: :collection
  end

  # ログイン機能
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post 'guest_login', to: 'user_sessions#guest_login'

  # ユーザー機能
  resources :users, only: %i[new create destroy]

  # 静的なページ
  get 'static_pages/top'
  root 'static_pages#top'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
# frozen_string_literal: true

class Diary < ApplicationRecord
  belongs_to :user

  enum good_or_bad: { good: 0, bad: 1 }

  validates :good_or_bad, presence: true
  validates :review_the_day, length: { maximum: 400 }
  validates :for_me_tommorrow, length: { maximum: 400 }
  validates :start_time, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :nickname, presence: true, length: { maximum: 20 }
  validates :email, uniqueness: true, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 8, maximum: 20 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  has_many :diaries, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  private

  def not_authenticated
    redirect_to login_path, alert: 'ログインしてください'
  end

  def already_logged_in
    redirect_to diaries_path if current_user
  end
end

app/controllers/diaries_controller.rb
# frozen_string_literal: true

class DiariesController < ApplicationController
  before_action :require_login
  before_action :duplication_check, only: %i[new create]

  def index
    @diaries = current_user.diaries
  end

  def new
    @diary = Diary.new
  end

  def create
    @diary = Diary.new(diary_params)
    if @diary.save
      redirect_to completion_diaries_path
    else
      flash.now[:danger] = '日記の作成に失敗しました'
      render 'form'
    end
  end

  def show
    @diary = Diary.find_by(user: current_user, start_time: params[:id].to_time)
  end

  def completion; end

  private

  def diary_params
    params.require(:diary).permit(:good_or_bad, :review_the_day, :for_me_tommorrow,
                                  :user_id).merge(user_id: current_user.id, start_time: Time.current.beginning_of_day)
  end

  def duplication_check
    redirect_to diaries_path, notice: '今日の日記はすでに登録済みです' if Diary.find_by(user: current_user,
                                                                         start_time: Time.current.beginning_of_day)
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  before_action :already_logged_in

  def top; end
end

app/controllers/user_sessions_controller.rb
# frozen_string_literal: true

class UserSessionsController < ApplicationController
  before_action :already_logged_in, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to(diaries_path, notice: 'ログインに成功しました')
    else
      flash.now[:alert] = 'ログインに失敗しました'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'ログアウトしました')
  end

  def guest_login
    @guest_user = User.create(
    nickname: 'ゲスト',
    email: SecureRandom.alphanumeric(10) + "@guest.com",
    password: 'password',
    password_confirmation: 'password'
    )
    auto_login(@guest_user)
    redirect_to diaries_path, success: 'ゲストとしてログインしました'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :already_logged_in, only: %i[new create]

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      redirect_to diaries_path, notice: 'ユーザー登録が完了しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy!
    redirect_to root_path, notice: 'ユーザーが削除されました'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/diaries/_diary.html.erb
<div>
  <p>良い1日だった？: <%= diary.good_or_bad_i18n %></p>
</div>
<div>
  <p>振り返り: <%= diary.review_the_day %>
</div>
<div>
  <p>明日の自分へ: <%= diary.for_me_tommorrow %>
</div>

app/views/diaries/_form.html.erb
<%= form_with model: diary do |f| %>
  <div class="mt-3">
    <%= f.label :good_or_bad, "今日(#{l(Time.current, format: :short)})は良い1日だった？", class:"form-label" %>
    <%= f.select :good_or_bad,[ ["はい", "good"], ["いいえ", "bad"] ], class:"form-control" %>
  </div>
  
  <div class="mt-3">
    <%= f.label :review_the_day, "今日(#{l(Time.current, format: :short)})の振り返り(400文字以内)", class:"form-label" %>
    <%= f.text_area :review_the_day, class:"form-control" %>
  </div>
  
  <div class="mt-3">
    <%= f.label :for_me_tommorrow, "明日(#{l(Time.current.tomorrow, format: :short)})の自分へ(400文字以内)", class:"form-label" %>
    <%= f.text_area :for_me_tommorrow, class:"form-control"%>
  </div>

  <div class="text-center mt-3">
    <%= f.submit class:'btn btn-primary' %>
  </div>

  <div class="text-center mt-3">
    <%= link_to "カレンダーに戻る", diaries_path %>
  </div>

<% end %>

app/views/diaries/completion.html.erb
<div class="container text-center">
  <h1 class="my-4">今日も1日お疲れ様です。</h1>
  <h5>今日の日記の登録は完了しました。</h5>
  <div class="mt-5">
    <%= link_to "カレンダーへ", diaries_path %>
  </div>
</div>

app/views/diaries/index.html.erb
<div class="container">
  <h1>カレンダー</h1>

  <%= month_calendar events: @diaries do |date, diaries| %>
    <%= link_to date.day, diary_path(date.to_s) %>
    <% diaries.each do |diary| %>
      <div>
        <% if diary.good? %>
          <i class="far fa-laugh-beam good-icon"></i>
        <% else %>
          <i class="far fa-grimace bad-icon"></i>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <div class="text-center mt-4">
    <% if current_user.diaries.find_by(start_time: Time.current.beginning_of_day) %>
      <%= link_to new_diary_path, class: 'btn btn-primary disabled' do %>
        今日は入力済みです<i class="fas fa-pencil-alt"></i>
      <% end %>
    <% else %>
      <%= link_to new_diary_path, class: 'btn btn-primary' do %>
        今日の日記を入力する<i class="fas fa-pencil-alt"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/diaries/new.html.erb
<div class="container">
  <h1>日記入力画面</h1>
  <%= render 'form', diary: @diary %>
</div>

app/views/diaries/show.html.erb
<div class="container">
  <h2 class="my-4"><%= l params[:id].to_time %>の日記</h2>
  <% if @diary %>
    <%= render 'diary', diary: @diary %>
  <% else %>
    <h5 class="text-center">この日は日記を書いていません</h5>
  <% end %>
  <div class="text-center mt-4">
    <%= link_to "カレンダーに戻る", diaries_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OddECalendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div>
      <p id="notice"><%= flash[:notice] %></p>
      <p id="alert"><%= flash[:alert] %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "日記カレンダーアプリ", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.nickname %>
            <i class="fas fa-user"></i>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <%= link_to "ログアウト", logout_path, method: :delete, class: "dropdown-item" %>
            <li><hr class="dropdown-divider"></li>
            <%= link_to "アカウント削除", user_path(current_user), method: :delete, data: { confirm: 'アカウントを削除してもよろしいですか？' }, class: "dropdown-item text-danger" %>
          </ul>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", login_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/static_pages/top.html.erb
<div class="container text-center">
  <h1 class="fw-bold my-5">日記カレンダーアプリ</h1>

  <p>1日の終わりを日記で振り返ることで、毎日を大切に生きることができるアプリ</p>

  <div class="row mt-5">
    <div class="col">
      <%= link_to "新規登録", new_user_path, class:"btn btn-primary" %>
    </div>
    <div class="col">
      <%= link_to "ゲストログイン", guest_login_path, class:"btn btn-warning", method: :post %>
    </div>
    <div class ="col">
      <%= link_to "ログイン", login_path, class:"btn btn-primary" %>
    </div>
  </div>
</div>

app/views/user_sessions/_form.html.erb
<%= form_with model: @user, url: login_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :email, class:"form-label" %><br />
    <%= f.text_field :email, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :password, class:"form-label" %><br />
    <%= f.password_field :password, class:"form-control" %>
  </div>
  <div class="actions text-center mt-3">
    <%= f.submit "ログイン", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="container">
  <h1>ログイン</h1>
  <%= render 'form' %>
  <div class="text-center mt-3">
    <%= link_to "アカウントをお持ちでない方は新規登録", new_user_path %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nickname, class:"form-label" %>
    <%= form.text_field :nickname, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :email, class:"form-label" %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :password, class:"form-label" %><br />
    <%= form.password_field :password, class:"form-control" %>
  </div>

  <div class="field">
   <%= form.label :password_confirmation, class:"form-label"%><br />
   <%= form.password_field :password_confirmation, class:"form-control" %>
  </div>


  <div class="actions text-center mt-3">
    <%= form.submit class:"btn btn-primary" %>
  </div>

<% end %>

app/views/users/new.html.erb
<div class="container">
  <h1>新規登録</h1>

  <%= render 'form', user: @user %>
  
  <div class="text-center mt-3">
    <%= link_to "アカウントをお持ちの方はログイン", login_path %>
  </div>

</div>